// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: small

#include "../ui.h"

void ui_ha_switches2_screen_init(void)
{
ui_ha_switches2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ha_switches2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ha_switches2, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ha_switches2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dropdown = lv_obj_create(ui_ha_switches2);
lv_obj_set_width( ui_dropdown, 214);
lv_obj_set_height( ui_dropdown, 164);
lv_obj_set_x( ui_dropdown, 22 );
lv_obj_set_y( ui_dropdown, 268 );
lv_obj_clear_flag( ui_dropdown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_dropdown, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_dropdown, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dropdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_dropdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_dropdown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_dropdown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dropdown_label = lv_label_create(ui_dropdown);
lv_obj_set_width( ui_dropdown_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dropdown_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dropdown_label, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_dropdown_label,"DropDown");
lv_obj_set_style_text_color(ui_dropdown_label, lv_color_hex(0x9E9E9E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dropdown_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_dropdown_label, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dropdown_btn = lv_dropdown_create(ui_ha_switches2);
lv_dropdown_set_options( ui_dropdown_btn, "Option 1\nOption 2\nOption 3\nOption 4\nOption 1\nOption 1\nOption 2\nOption 3\nOption 4\nOption 2\nOption 3\nOption 4" );
lv_obj_set_width( ui_dropdown_btn, 150);
lv_obj_set_height( ui_dropdown_btn, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dropdown_btn, -109 );
lv_obj_set_y( ui_dropdown_btn, 74 );
lv_obj_set_align( ui_dropdown_btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dropdown_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_color(ui_dropdown_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_dropdown_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_dropdown_btn, lv_color_hex(0x529D53), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dropdown_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_dropdown_btn, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_dropdown_btn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_dropdown_btn), lv_color_hex(0xC3C3C3),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_dropdown_btn), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_dropdown_btn), lv_color_hex(0x4F4F4F),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_dropdown_btn), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(lv_dropdown_get_list(ui_dropdown_btn), lv_color_hex(0x2F2F2F),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_dropdown_btn), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_dropdown_btn), lv_color_hex(0x529D53),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_dropdown_btn), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_ha_switches2_label = lv_label_create(ui_ha_switches2);
lv_obj_set_width( ui_ha_switches2_label, 316);
lv_obj_set_height( ui_ha_switches2_label, 38);
lv_obj_set_x( ui_ha_switches2_label, 82 );
lv_obj_set_y( ui_ha_switches2_label, 58 );
lv_label_set_text(ui_ha_switches2_label,"Switches");
lv_obj_set_style_text_color(ui_ha_switches2_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ha_switches2_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ha_switches2_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ha_switches2_label, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

}
