// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: medium

#include "../ui.h"

void ui_ha_switches2_screen_init(void)
{
ui_ha_switches2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ha_switches2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ha_switches2, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ha_switches2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ha_switches2_label = lv_label_create(ui_ha_switches2);
lv_obj_set_width( ui_ha_switches2_label, 316);
lv_obj_set_height( ui_ha_switches2_label, 38);
lv_obj_set_x( ui_ha_switches2_label, 82 );
lv_obj_set_y( ui_ha_switches2_label, 58 );
lv_label_set_text(ui_ha_switches2_label,"Switches");
lv_obj_set_style_text_color(ui_ha_switches2_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ha_switches2_label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ha_switches2_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ha_switches2_label, &ui_font_font0, LV_PART_MAIN| LV_STATE_DEFAULT);

}
