// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: small

#ifndef _SMALL_UI_H
#define _SMALL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ha_sensors
void ui_ha_sensors_screen_init(void);
extern lv_obj_t *ui_ha_sensors;
extern lv_obj_t *ui_ha_sensors_label;
extern lv_obj_t *ui_sensor1_btn;
extern lv_obj_t *ui_sensor1_logo;
extern lv_obj_t *ui_sensor1_label;
extern lv_obj_t *ui_sensor1_data;
extern lv_obj_t *ui_sensor1_unit;
extern lv_obj_t *ui_sensor2_btn;
extern lv_obj_t *ui_sensor2_logo;
extern lv_obj_t *ui_sensor2_label;
extern lv_obj_t *ui_sensor2_data;
extern lv_obj_t *ui_sensor2_unit;
extern lv_obj_t *ui_sensor3_btn;
extern lv_obj_t *ui_sensor3_logo;
extern lv_obj_t *ui_sensor3_label;
extern lv_obj_t *ui_sensor3_data;
extern lv_obj_t *ui_sensor3_unit;
extern lv_obj_t *ui_sensor4_btn;
extern lv_obj_t *ui_sensor4_logo;
extern lv_obj_t *ui_sensor4_label;
extern lv_obj_t *ui_sensor4_data;
extern lv_obj_t *ui_sensor4_unit;
extern lv_obj_t *ui_logo;
extern lv_obj_t *ui_sensor1_btn1;
// SCREEN: ui_ha_switches
void ui_ha_switches_screen_init(void);
extern lv_obj_t *ui_ha_switches;
extern lv_obj_t *ui_ha_switches_label;
extern lv_obj_t *ui_Button;
extern lv_obj_t *ui_button_logo;
extern lv_obj_t *ui_button_label;
extern lv_obj_t *ui_toggle;
extern lv_obj_t *ui_toggle_label;
extern lv_obj_t *ui_toggle_btn;
extern lv_obj_t *ui_slider;
extern lv_obj_t *ui_slider_label;
extern lv_obj_t *ui_slider_data;
extern lv_obj_t *ui_slider_unit;
void ui_event_slider_btn( lv_event_t * e);
extern lv_obj_t *ui_slider_btn;
extern lv_obj_t *ui_dropdown;
extern lv_obj_t *ui_dropdown_btn;
extern lv_obj_t *ui_dropdown_label;
extern lv_obj_t *ui_arc;
void ui_event_arc_btn( lv_event_t * e);
extern lv_obj_t *ui_arc_btn;
extern lv_obj_t *ui_arc_label;
extern lv_obj_t *ui_arc_data;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ic_temp_png);   // assets\ic_temp.png
LV_IMG_DECLARE( ui_img_ic_hum_png);   // assets\ic_hum.png
LV_IMG_DECLARE( ui_img_ic_tvoc_png);   // assets\ic_tVOC.png
LV_IMG_DECLARE( ui_img_ic_co2_png);   // assets\ic_co2.png
LV_IMG_DECLARE( ui_img_ha_logo32_png);   // assets\ha_logo32.png
LV_IMG_DECLARE( ui_img_ic_switch1_off_png);   // assets\ic_switch1_off.png
LV_IMG_DECLARE( ui_img_wifi_2_png);   // assets\wifi_2.png
LV_IMG_DECLARE( ui_img_wifi_3_png);   // assets\wifi_3.png
LV_IMG_DECLARE( ui_img_wifi_1_png);   // assets\wifi_1.png
LV_IMG_DECLARE( ui_img_location2_png);   // assets\location2.png
LV_IMG_DECLARE( ui_img_co2_png);   // assets\co2.png
LV_IMG_DECLARE( ui_img_humidity_1_png);   // assets\humidity_1.png
LV_IMG_DECLARE( ui_img_temp_2_png);   // assets\temp_2.png
LV_IMG_DECLARE( ui_img_humidity_2_png);   // assets\humidity_2.png
LV_IMG_DECLARE( ui_img_temp_1_png);   // assets\temp_1.png

LV_FONT_DECLARE( ui_font_font0);
LV_FONT_DECLARE( ui_font_font2);
LV_FONT_DECLARE( ui_font_font3);
LV_FONT_DECLARE( ui_font_font4);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
